version: '3.8'
services:
  backend:
    container_name: backend
    image: warmupbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    networks:
      - warmupapp
      
  frontend:
    container_name: frontend
    image: warmupfront
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - warmupapp

networks:
  warmupapp: